### ISSUE TITLE
Error with InAppFragment

### ISSUE THREAD

**Issue by fabiocarballo** [mixpanel/mixpanel-android#295] opened 2015-12-30 10:34 UTC
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
       at android.app.BackStackRecord.commit(BackStackRecord.java:575)
       at com.mixpanel.android.mpmetrics.InAppFragment.cleanUp(InAppFragment.java:224)
       at com.mixpanel.android.mpmetrics.InAppFragment.onSaveInstanceState(InAppFragment.java:206)
       at android.app.Fragment.performSaveInstanceState(Fragment.java:1845)
       at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1596)
       at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1653)
       at android.app.Activity.onSaveInstanceState(Activity.java:1297)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:522)
       at android.app.Activity.performSaveInstanceState(Activity.java:1245)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1229)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3527)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3586)
       at android.app.ActivityThread.access$1200(ActivityThread.java:171)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1336)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5679)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ryanseams** [comment] 2015-12-30 17:21
Hi @fabiocarballo thanks for reporting this!

It looks like this is the same crash as https://github.com/mixpanel/mixpanel-android/issues/284? If you can provide additional test conditions around how this is reproduced from your end (different than those in the above issue) that would be awesome so we can look into this further.

**Comment by fabiocarballo** [comment] 2015-12-30 17:51
Hey @ryanseams ! I think it should be related to #284 . However, I have been trying to reproduce this without success. I just have this information due to be using Crashlytics on our app. As in the other issue it should be caused when displaying a notification on activity that is not on top of the stack

**Comment by yinfeiru** [comment] 2016-01-22 00:44
@fabiocarballo Sorry for the late response. Are you still having this issue? If so, please let me know
1. the library version
2. the Android OS version that this failure happens on

More context about this crash:
When the user goes from one activity to another, our library tries to remove all the pending fragment transactions by calling `InAppFragment.cleanUp`. It does so by doing https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/InAppFragment.java#L224. `FragmentTransaction.commit` then checks if onSaveInstanceState of the current activity has been called. If so, it throws an exception. On 2014-09-10, we made a patch to move the `cleanUp()` call to `onPause()` to workaround this potential crash. According to the Android doc, onSaveInstanceState `is called before an activity may be killed`, which is after `onPause`. Having `cleanUp` in `onPause` would eliminate the possibility of this type of crash. So, the lib version and the Android OS version would help me to understand the problem here better.

**Comment by fabiocarballo** [comment] 2016-01-25 11:20
hey @yinfeiru !

Yes, we still have this issue. (We done a workaround to avoid it, but it is not the ideal solution). 

I was able to reproduce this kind of issue (crashing when presenting in-apps) by doing the following steps:

1. Start Activity
2. In the **onResume** try to fetch an in-app and present with showNotificationsIfAvailable
3. In the **onResume** open another activity

This causes the activity to be not available when the assynchronous work on fetching the notification is available.

The problem appear on Android 4.* , 5.* and 6.* .. There is no distinction.

**Comment by yinfeiru** [comment] 2016-01-25 23:08
@fabiocarballo Thanks for writing back and I'm sorry to hear that you are still suffering this issue. And, yes, our `showNotificationsIfAvailable` API is not smart enough to handle it at this point. I'll definitely find a way to fix it. 

To this particular issue, is it possible to let Mixpanel show the notifications automatically with the following config in your Manifest?
```
        <meta-data android:name="com.mixpanel.android.MPConfig.AutoShowMixpanelUpdates"
               android:value="true" />
```
Or, is it OK if you move the `showNotificationsIfAvailable` call to onStart?
Is it possible to let me know your workaround?

**Comment by fabiocarballo** [comment] 2016-01-27 10:12
On the activity where I show the notifications I had to add a control variable to check whether the acitvity was available or not. (Not pretty, but working)

The code looks something like this:

```java 
private boolean mIsActivityRunning = false;

 public void onPause() {
  super.onPause()
   mIsActivityRunning = false;
 }
public void onResume() {
  super.onResume()
  mIsActivityRunning = true;
  
}

public void fetchNotification() {
   InAppNotification notif  =  mixpanelInstance.getPeople().getNotificationIfAvailable()
  if(mIsActivityRunning) {
    mixpanelInstance.showNotification(notif, this)
  }
}
```

Thank you @yinfeiru

**Comment by yinfeiru** [comment] 2016-01-27 18:01
#300 
I have a PR to fix this. This fix will be available in the next release.

**Comment by fabiocarballo** [comment] 2016-01-28 14:26
Good to know! :)

**Comment by yinfeiru** [comment] 2016-02-01 22:55
Closing this.

**Closed by yinfeiru** 2016-02-01 22:55 UTC
Labels: bug

**Comment by artesa** [comment] 2016-10-31 16:59
Still facing this issue on v4.9.2
Looks like the problem is in calling `cleanUp()` in `onSaveInstanceState()` (is it really necessary, after doing it in `onPause()`)?

Steps:
0. send notifications
1. open the app
2. see the fullscreen notifications screen
3. tap on the action button
expected result: AnotherActivity is launched
actual result: app crashes

Can you please advice?
We're calling showNotificationIfAvailable() not from an activity, but from a fragment. May the problem happen due to it?

`10-31 16:10:30.646: E/AndroidRuntime(23056): FATAL EXCEPTION: main
10-31 16:10:30.646: E/AndroidRuntime(23056): Process: com.example, PID: 23056
10-31 16:10:30.646: E/AndroidRuntime(23056): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.BackStackRecord.commit(BackStackRecord.java:575)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at com.mixpanel.android.mpmetrics.InAppFragment.cleanUp(InAppFragment.java:234)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at com.mixpanel.android.mpmetrics.InAppFragment.onSaveInstanceState(InAppFragment.java:216)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.Fragment.performSaveInstanceState(Fragment.java:1845)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1596)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1653)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.Activity.onSaveInstanceState(Activity.java:1281)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:564)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:502)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at com.example.activity.BaseActivity.onSaveInstanceState(BaseActivity.java:337)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at com.example.activities.MyActivity.onSaveInstanceState(MyActivity.java:811)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.Activity.performSaveInstanceState(Activity.java:1229)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1229)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3491)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.ActivityThread.access$1200(ActivityThread.java:175)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1330)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.os.Looper.loop(Looper.java:146)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at android.app.ActivityThread.main(ActivityThread.java:5602)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
10-31 16:10:30.646: E/AndroidRuntime(23056): 	at dalvik.system.NativeStart.main(Native Method)
10-31 16:10:30.676: W/ActivityManager(2436):   Force finishing activity com.example/.activities.AnotherActivity`

Thanks!

**Comment by artesa** [comment] 2016-10-31 17:27
From the code of InAppFragment I see that this clean up should have been done in onPause(), and the respective flag should have been set there. If so, clean up from onSaveInstanceState() should have never happened, as it checks that flag.

Does that mean that onPause() was never called?
What usage case it can be then?

**Comment by artesa** [comment] 2016-10-31 17:58
As there is "race condition" between callings of this method from onPause() and from onSaveInstanceState(), it's obvious that in our case onSaveInstanceState() was called earlier. Looks like it's unreliable, though, to commit transactions from state...

**Comment by artesa** [comment] 2016-11-01 10:16
As far as I see from Android support library code, for API 11 and higher:

1. When activity is treated as "state-saved", no more fragment transactions are allowed.
1. Activity starts to be treated as "state-saved" **in the midst** of super.onSaveInstanceState() callback
  * it happens **after** saving state of activity itself (passing the callback up in the classes hierarcy)
  * but **before** calling onSaveInstanceState() for activities **fragments**
2. So, committing any transactions from onSaveInstanceState():
  * **from activity** - is ok, if we do it before calling the super method
  * **from fragment** - is always forbidden and causes crash

So, the only solution I see is:
* to remove the cleanUp() call from onSaveInstanceState() - it's not doing good at all;
* in onPause() call, to replace `commit()` with `commitAllowStateLoss()`, to prevent crashes in case when onSaveInstanceState() was called prior to onPause() and activity is actually "state-saved".

**It will fix the crash.**
There are possible **side-effect** -- in some cases (when onPause() was called after onSaveInstanceState()) user will return to the activity and, **if the activity was killed** due to memory pressure, they will see MixPanel notification fragment unremoved. I hope they can press "Back" in such a case, so it will be definitely better than crash...
Also, some analytics can be added, to track the amount of such cases. **I believe that it's a rare case** (otherwise you'd face this issue much earlier). I'd suggest to think of a solution to this side-effect only if we'll see that there is really a significant amount of such cases.

**Comment by yinfeiru** [comment] 2016-11-01 18:19
Thanks for looking into this issue and all the info! It's really helpful!!

For `to remove the cleanUp() call from onSaveInstanceState() - it's not doing good at all;`, I don't think that's the case. According to the documentation, `onSaveInstanceState` might get called before `onPause`:
`There are no guarantees about whether it will occur before or after onPause().`

We want to make sure `cleanUp` always gets called before `onSaveInstanceState`. So, we have to have the `cleanUp` call in `onSaveInstanceState`.

I don't have a concrete solution on top of my mind for now. I think we can do something similar to https://github.com/mixpanel/mixpanel-android/pull/300 - catch the exception but do nothing in this case. As you mentioned, not removing the notification is definitely better than crash.

**Comment by yinfeiru** [comment] 2016-11-01 22:05
@artesa I'm working on reproducing this issue. 
I have an activity which has a fragment. `showNotificationIfAvailable` gets called in the `onResume()` of the fragment. The CTA of the notification is `test://test` which opens up a different activity when I click the button.

I've tried it multiple times but didn't see the crash. Can you let me know if it's similar to what you are doing?

Also, replacing `commit` with `commitAllowStateLoss` would avoid this crash for sure. What I want to know is that if https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/InAppFragment.java#L200 removes the notification the next time you go back to that fragment. If so, there's no side-effect with this change.

I found an interesting article about this issue if you are interested.
http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html

**Comment by artesa** [comment] 2016-11-02 12:21
@yinfeiru First of all, thank you for taking a look at this issue. And I'm very much grateful for quick response!

>We want to make sure cleanUp always gets called before onSaveInstanceState. So, we have to have the cleanUp call in onSaveInstanceState.

I agree that clean-up should be done somewhere. My point is that Fragment's `onSaveInstanceState()` is too late for doing that anyway. I checked it on various devices - it's always crash when it gets there.

The right place would have been Activity's `onSaveInstanceState()`... if we could get there.

> What I want to know is that if https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/InAppFragment.java#L200 removes the notification the next time you go back to that fragment. If so, there's no side-effect with this change.

Good point, it will protect from side-effect. But looks like it will work only for cases when Activity was not destroyed. If it was, `onCreate()` will be called, and you set `mCleanedUp = false;` in `onCreate()`. I believe, saving this variable to fragment's bundle and then restoring it in `onCreate()` will make the fix overall.

**Comment by artesa** [comment] 2016-11-02 12:31
Regarding steps to reproduce it -- not sure I will help you a lot. We were able to repro it only once, and then were're working with logs and stub code. 
What I done was a simple test app which has one activity, the activity contains a single fragment, being added in `onCreate()`. I try to remove in inside Fragment's `onSaveInstanceState()` -- and it constantly produces a crash. When I move it to Activity's `onSaveInstanceState()`, before calling the super method, it works well instead.
(You can find the explanation of that phenomenon in the Activity's and FragmentManager's code, or see my comment above.)
So, it's a simple test not to the whole issue but just for this specific approach.

We might be more lucky to reproduce the issue, but the process is very much complicated (we need to contact with out server team, ask them to send us some notifications, and then wait for the notifications to come, and then tap, and in some rare cases we might see the crash.) 

Besides, maybe there is an easier way to test such stuff, like using Charles?.. I've seen you are using Selendroid to test the library, but I'm not sure it will make things easier in our particular case...

**Comment by artesa** [comment] 2016-11-03 10:00
@yinfeiru Any updates?
If you want to discuss it in more details, let's have a voice call via Skype (anna.illina.od)

**Comment by baboog** [comment] 2017-03-07 12:13
facing this issue alot on samsung s3 mini
any updates ?


```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1280)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1291)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:548)
       at android.app.BackStackRecord.commit(BackStackRecord.java:532)
       at com.mixpanel.android.mpmetrics.InAppFragment.a(SourceFile:234)
       at com.mixpanel.android.mpmetrics.InAppFragment.onSaveInstanceState(SourceFile:216)
       at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1542)
       at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1602)
       at android.app.Activity.onSaveInstanceState(Activity.java:1210)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(SourceFile:567)
       at android.support.v7.app.AppCompatActivity.onSaveInstanceState(SourceFile:511)
       at android.app.Activity.performSaveInstanceState(Activity.java:1158)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1230)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:2997)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3056)
       at android.app.ActivityThread.access$1000(ActivityThread.java:134)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1245)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)


```
and 

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1343)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1361)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:728)
       at android.app.BackStackRecord.commit(BackStackRecord.java:704)
       at com.mixpanel.android.mpmetrics.InAppFragment.cleanUp(InAppFragment.java:234)
       at com.mixpanel.android.mpmetrics.InAppFragment.onSaveInstanceState(InAppFragment.java:216)
       at android.app.Fragment.performSaveInstanceState(Fragment.java:2299)
       at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1620)
       at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1677)
       at android.app.Activity.onSaveInstanceState(Activity.java:1457)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:567)
       at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
       at android.app.Activity.performSaveInstanceState(Activity.java:1383)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1286)
       at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4482)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3854)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3917)
       at android.app.ActivityThread.access$1200(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5951)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

```
