### ISSUE TITLE
Problem with rtl layout in version 4.6.0 and later

### ISSUE THREAD

**Issue by alamkanak** [mixpanel/mixpanel-android#240] opened 2015-07-24 17:43 UTC
Having problem with right-to-left layouts when using versions > 4.5.3. In the screenshot below, the toolbar is supposed to be right to left in both the images but it is left to right when version 4.6.0 is used.

![untitled-1](https://cloud.githubusercontent.com/assets/3194741/8880729/9ceda67c-325c-11e5-9a16-a1591bcceb1b.png)

**Reproduce**
1. Open a new android studio project.
2. [Add rtl support by changing the manifest file](http://android-developers.blogspot.com/2013/03/native-rtl-support-in-android-42.html).
3. Add mixpanel 4.6.0 as a dependency in the `build.gradle` file.
4. Initialize mixpanel in the main activity.
5. Change your device (preferably lollipop) language to, say, Arabic.
6. Run the app in that device. Notice that the toolbar is still left-to-right.
7. Change the mixpanel version to 4.5.3.
8. Run again. Notice that the toolbar is now displaying correctly.

**Comment by ryanseams** [comment] 2015-08-25 18:53
thanks for bringing this up @alamkanak! i confirmed this issue is occurring in 4.6.+ versions of the library and traced this back to [these commits](https://github.com/mixpanel/mixpanel-android/compare/d643e71630d10287d552f0ee3a1db1774ba489ec...cafd08f9856a9df6c127fb78719c4d884ee4535e)

so sorry about this -- it would appear some commits which were thought to be minor caused unintended effects on the ability to render RTL layouts

in the meantime while we find a fix for this, you can use the following version in your project to use RTL with A/B testing (note this does not contain any bug fixes since v4.6.0 was released):
```compile 'com.mixpanel.android:mixpanel-android:4.5.4-RC2'```

**Comment by reemsherman** [comment] 2015-08-31 08:08
haaaaaaaaaaaaaaaaaaaaaaaa!
I just spent at least a full day work on this. @alamkanak - thank you so much for this. You just saved my week!

**Comment by rejasupotaro** [comment] 2016-01-07 08:05
Is it fixed? I'm in trouble with a similar problem...

RTL would be disabled when I call `MixpanelAPI.getInstance`.

<img width="512" alt="screen shot 2016-01-07 at 16 54 31" src="https://cloud.githubusercontent.com/assets/883148/12165218/61e7bffa-b55f-11e5-9cce-8a76a7703e3a.png">

The library version is 4.7.0. Minimum sample project is here: https://github.com/rejasupotaro/RtlWithMixpanel

**Comment by ryanseams** [comment] 2016-01-07 17:45
hi @rejasupotaro! this issue is not fixed so the current workaround is still as mentioned above:

"in the meantime while we find a fix for this, you can use the following version in your project to use RTL with A/B testing (note this does not contain any bug fixes since v4.6.0 was released):
compile ```'com.mixpanel.android:mixpanel-android:4.5.4-RC2'```"

**Comment by rejasupotaro** [comment] 2016-01-08 00:27
Ah, okay. I will use v4.5.4-RC2 for now. Thank you for your quick reply :beers:

**Comment by imrihe** [comment] 2016-01-21 13:51
we also encounter the issue - please fix

**Comment by nadavfima** [comment] 2016-01-21 13:59
same here :(
went back to V4.5.4 for now

**Comment by yinfeiru** [comment] 2016-01-26 21:50
Thanks for writing in guys and sorry for the late response. I'll make sure to look into this in the next few days!

**Comment by yinfeiru** [comment] 2016-01-27 21:45
This bug has been fixed in #310 . It will be available in the next release which is coming soon.

**Closed** 2016-02-01 22:58 UTC
Labels: bug

**Comment by mzekrallah** [comment] 2016-02-03 18:03
any estimated time for releasing this fix ? we have apps suffering from this bug in production .. thanks

**Comment by NammariMarkavip** [comment] 2016-02-10 12:00
+1

**Comment by patedit** [comment] 2016-02-10 16:14
@NammariMarkavip @mzekrallah @alamkanak @nadavfima @imrihe @rejasupotaro @reemsherman New release 4.8.0 fixes this issue :)

**Comment by hmedat2008** [comment] 2016-02-14 16:46
Many Thanks

**Comment by rejasupotaro** [comment] 2016-02-15 00:19
It works correctly! Congrats :tada: Thank you :smile:
