### ISSUE TITLE
java.lang.VerifyError at basic track() in Android version 4.4.2

### ISSUE THREAD

**Issue by reddy6362** [mixpanel/mixpanel-android#309] opened 2016-01-27 07:39 UTC
Recently I have integrated *MixPanel (V 4.6.4)* in to one of my android application and I am good at getting logs. But during our testing, we observed that the application(Mixpanel tracking code) is getting crashed in couple of Android versions.

Please find the details below.  

**Exception:**
java.lang.VerifyError: com/analytics/mixpanel/MixPanelManager
                at com.unidos.selfservice.LoginFragment.onCreateView(LoginFragment.java:69)
                at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
                at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
                at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
                at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239)
                at android.app.Activity.performStart(Activity.java:5322)
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2569)
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653)
                at android.app.ActivityThread.access$800(ActivityThread.java:156)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:157)
                at android.app.ActivityThread.main(ActivityThread.java:5872)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:515)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:668)
                at dalvik.system.NativeStart.main(Native Method)

**Tracking Code:**
*In Fragment:*

        MixPanelManager.pushScreenView((AppCompatActivity)getActivity(), "Login");
---------------------------------------
**MixPanelManager Code:**
    public static void pushScreenView(AppCompatActivity activity, String screenName) {
            try {
                MixpanelAPI mixpanelAPI = ((SelfServiceApplication) activity.getApplication()).getMixPanelInstance(activity);
                mixpanelAPI.track("Screen : " + screenName);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }

-----------------------------------------
**SelfServiceApplication Code:**
    public MixpanelAPI getMixPanelInstance(Context context) {
        if (mixpanelAPI == null) {
            return MixpanelAPI.getInstance(context, Globals.MIXPANEL_TOKEN);
        } else {
            return mixpanelAPI;
        }
    }

-------------------------------------------

**Dependencies used in the project:**

{
compile 'com.android.support:appcompat-v7:22.2.0'
compile 'com.google.android.gms:play-services:7.0.0'
compile 'com.google.code.gson:gson:2.3'
compile 'com.facebook.android:facebook-android-sdk:4.6.0'
// MixPanel
compile "com.mixpanel.android:mixpanel-android:4.6.4"
compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
    transitive = true;
}

OS Version we observed the issue: **Android 4.4.2 (Asus Nexus 7 Tablet and HTC One M8)**.
We tested with Samsung devices running on same OS version, but app is working good. I am not sure what is happening with these devices.

**Note:** Not using any in-app notifications or other features of Mixpanel. Just tracking event in the Fragment of an Activity. We are facing the same issue with tracking in single Activity without any navigation.

Can you please help me fixing this issue. This is a blocker for us to proceed.

**Comment by ryanseams** [comment] 2016-01-27 21:45
hi @reddy6362 thanks for writing in! based on the fact you are getting java.lang.VerifyError, there could be a number of issues occurring here. this error means that you're referencing a class that Dalvik cannot load, which has a large number of potential causes.

is it possible to check your logs from right before this crash occurs? this will let us know specifically which class reference is causing this crash. the line you would be looking for looks like:

```
01-27 13:13:21.406    1656-1656/PACKAGE_NAME I/dalvikvm﹕ Could not find method com.google.android.gms.common.api.GoogleApiClient.isConnected, referenced from method com.google.example.games.basegameutils.GameHelper.beginUserInitiatedSignIn
```

if you can let us know what class is referenced right before the crash occurs we can proceed with figuring out what the root cause of this issue is!

**Comment by patedit** [comment] 2016-02-04 00:49
Hi @reddy6362 ! It looks like your own class `com.analytics.mixpanel.MixpanelManager` could not be loaded for different reasons (as pointed by @ryanseams). I may be wrong but I do not think this is related to the library but a mistake on your end.

By the way, you do not need to pass the activity object by `getActivity()` if you only need the context. It may leak your app in the future depending on the implementation. And feel free to use our latest SDK version (4.7.0) instead of 4.6.4.

I'm closing this ticket, but feel free to open a new one if you see any problems with the library itself!

**Closed by patedit** 2016-02-04 00:49 UTC

**Comment by reddy6362** [comment] 2016-03-24 11:48
Hi,
The issue is happenning in some versions of Android versions. Specific to 4.4.2

Is this the issue with try catch block around tracking code in my app.

**Comment by patedit** [comment] 2016-03-24 17:40
@reddy6362 I want to make sure you understand that it's not a problem in Mixpanel library but in your project. Notice that it fails when loading your own class and `com.analytics.mixpanel.MixpanelManager`.
