### ISSUE TITLE
ImageStore.getImage(): OutOfMemoryError

### ISSUE THREAD

**Issue by Digisha** [mixpanel/mixpanel-android#308] opened 2016-01-26 21:49 UTC
- We have noticed OutOfMemoryError in our crash report tool for our app versions when we were using Mixpanel A/B testing. Most of our errors are happening on 4.1.2, 4.4.2 and 5.0 devices.

- I tried to update an image in our app with images of size 175KB and 139KB from A/B testing and I was able to reproduce the error.

- We are on  
>   compile 'com.mixpanel.android:mixpanel-android:4.7.0'

```
Stack Trace
_________________________________
0	java.lang.OutOfMemoryError
1		at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
2		at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:619)
3		at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:385)
4		at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:418)
5		at com.mixpanel.android.util.ImageStore.getImage(ImageStore.java:96)
6		at com.mixpanel.android.viewcrawler.EditProtocol.readBitmapDrawable(EditProtocol.java:406)
7		at com.mixpanel.android.viewcrawler.EditProtocol.convertArgument(EditProtocol.java:366)
8		at com.mixpanel.android.viewcrawler.EditProtocol.readEdit(EditProtocol.java:143)
9		at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.applyVariantsAndEventBindings(ViewCrawler.java:832)
10		at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.initializeChanges(ViewCrawler.java:423)
11		at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleVariantsReceived(ViewCrawler.java:750)
12		at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:311)
13		at android.os.Handler.dispatchMessage(Handler.java:99)
14		at android.os.Looper.loop(Looper.java:137)
15		at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by yinfeiru** [comment] 2016-02-01 22:54
#315 Closing this and will track this issue in the pr.

**Comment by diwanshuster** [comment] 2016-03-22 08:42
I am getting the exact same crash in version 4.8.0. What's the current status of this issue???

**Comment by ryanseams** [comment] 2016-03-24 17:43
@yinfeiru @patedit other users are also reporting this crash as occurring on 4.8.0. looks like we may consider reopening as it does not appear to be resolved.

**Comment by patedit** [comment] 2016-03-25 00:35
@diwanshuster @ryanseams Can you confirm that is `decodeFile` and not `decodeByteArray` the one that is throwing `OutOfMemoryError`?

**Comment by diwanshuster** [comment] 2016-03-25 04:52
@patedit YES, BitMapFactory.decodeFile seems to throw this error in my case.

**Comment by patedit** [comment] 2016-03-25 20:22
@diwanshuster Thanks! Do you have any background thread using a large amount of heap (i.e. creating bitmaps as well)? Are you able to reproduce the issue by yourself? What is the device and Android version that is crashing on? I am trying to reproduce the crash with no luck on my end. The fix that we included checks the free available memory on the heap and I can only think that while we `decodeFile` a background thread is allocating memory.

**Comment by diwanshuster** [comment] 2016-03-30 06:12
@patedit The crash appears in Android version 4 (almost all versions) and 6.0 in almost all devices. I am not  able to deduce a case where a background thread in my code will allocate a memory on heap (especially for bitmaps) as we are not actively dealing with bitmaps in our application. Anyways, can you point out the use-case where the particular piece of code requiring decodeFile is getting executed.

**Comment by fred8** [comment] 2016-03-30 23:19
The answer to that problem is straight forward: the ImageStore class should have a cache on 2 levels. One disk based on a DiskLruCache (not the current impl.) and a memory cache based on a LruCache. That way the bitmap will not be recreate every single time (for the in app notification, this bitmap is recreated on every single network flush.
I already mention that - It *must* be fix

**Comment by fred8** [comment] 2016-03-30 23:20
BTW, we have a forked version of the library, we had to do it to avoid large production issues....

**Comment by Macarse** [comment] 2016-05-04 05:32
@fred8 can you submit a pr?

**Comment by patedit** [comment] 2016-07-05 18:03
Starting 4.9.0 we have a LRU cache on `ImageStore` that will prevent re-loading the same bitmaps for notifications, ab testing, etc.. Thanks everyone for your input 👍 Hope this gets resolved finally!

**Closed by patedit** 2016-07-05 18:03 UTC
Labels: bug
