### ISSUE TITLE
joinExperimentIfAvailable / addOnMixpanelUpdatesReceivedListener doesn't guarantee that the tweaks are up to date

### ISSUE THREAD

**Issue by fred8** [mixpanel/mixpanel-android#342] opened 2016-03-30 23:31 UTC
As said in the title. When we join an experiment and receive the mixpanel update callback; sometimes the tweaks variable are not up to date.
Would be **great** to have a fix for it

**Comment by fred8** [comment] 2016-04-05 00:47
Hey there! any updates on that?

**Comment by ryanseams** [comment] 2016-04-05 01:17
Hi @fred8 -- hope all is well!

Is it possible to elaborate on what you mean when you say "sometimes the tweak variables are not up to date"? Specifically, is the issue the tweaks are not updating quickly enough within the listener OR the tweaks are not updating to their expected values at all?

Any further info you can provide about the behavior you are seeing will assist us in being able to debug this further!

**Comment by fred8** [comment] 2016-04-05 20:06
Hi @ryanseams,

To turn it in a different way: the listener should be call as soon as the experiment as been actually joined and that the tweak variable contains the appropriated value -- which is not the case. The listener is called before. As the result, when we get the listener it's not certain that the tweak variables are up-to-date.

**Comment by fred8** [comment] 2016-04-07 22:05
Hey @ryanseams,

Do you have any ideas of what's going on?
Thank you!

**Comment by ryanseams** [comment] 2016-04-08 00:13
Hi @fred8 -- I just ran a test on this and am not seeing any issues with the tweaks being up to date. In my test I log the initial tweak value, then call another method where I join the A/B test and then print again the value of the tweak. You can see the result of this is the tweak value in the experiment being applied as expected, as you can see in the log below:

```
04-07 17:04:34.536 12147-12384/com.ryanseams.mixpanel_playground D/Variants: Tweak has been assigned as -1
04-07 17:04:34.546 12147-12384/com.ryanseams.mixpanel_playground D/Variants: Tweak has been assigned as 5
```

Is it possible to share what you are doing within your ```addOnMixpanelUpdatesReceivedListener```? Are you calling ```MixpanelAPI.getPeople().showNotificationIfAvailable(this)``` before accessing the value of the tweak variable?

**Comment by fred8** [comment] 2016-04-08 00:19
I'm using it to update some super properties.
showNotificationIfAvailable could be call before or after; how it's related?

**Comment by ryanseams** [comment] 2016-04-08 00:20
Sorry, the call is not to ```showNotificationIfAvailable``` it is to ```joinExperimentIfAvailable```. Are you joining the experiment before accessing the value of the tweaks?

One other consideration -- are you sending an event immediately after setting the super properties?

**Comment by fred8** [comment] 2016-04-08 00:22
Nope, we're doing a call to joinExperimentIfAvailable before trying accessing the tweaks.
Yes, potentially; why?

**Comment by ryanseams** [comment] 2016-04-08 23:48
@fred8 Can you confirm your listener looks something like:
```
mMixpanel.getPeople().addOnMixpanelUpdatesReceivedListener(new OnMixpanelUpdatesReceivedListener() {
            @Override
            public void onMixpanelUpdatesReceived() {
                int isIt = GroupIdTweak.get();
                Log.d("Variants", "GroupIdTweak has been assigned as " + isIt);
                boolean hiThere = HiThereTweak.get();
                Log.d("Variants", "HiThereTweak has been assigned as " + hiThere);
                mMixpanel.getPeople().joinExperimentIfAvailable();
                isIt = GroupIdTweak.get();
                Log.d("Variants", "GroupIdTweak has been assigned as " + isIt);
                hiThere = HiThereTweak.get();
                Log.d("Variants", "HiThereTweak has been assigned as " + hiThere);
            }
        });
```

Using this configuration and logging I can see there is potential for a log like:
```
04-08 16:29:01.528 26102-26240/com.ryanseams.mixpanel_playground V/MixpanelAPI.DChecker: Mixpanel decide server response was:
                                                                                         {"notifications":[],"surveys":[],"config":{"enable_collect_everything":false},"variants":[{"tweaks":[{"name":"GroupIdTweak","encoding":"l","maximum":null,"value":3,"minimum":null,"type":"number"},{"minimum":null,"type":"boolean","name":"hiThere","value":false,"maximum":null}],"actions":[],"id":31047,"experiment_id":15629}]}
04-08 16:29:01.538 26102-26316/com.ryanseams.mixpanel_playground D/Variants: GroupIdTweak has been assigned as -1
04-08 16:29:01.538 26102-26316/com.ryanseams.mixpanel_playground D/Variants: HiThereTweak has been assigned as true
04-08 16:29:01.538 26102-26316/com.ryanseams.mixpanel_playground D/Variants: GroupIdTweak has been assigned as -1
04-08 16:29:01.538 26102-26316/com.ryanseams.mixpanel_playground D/Variants: HiThereTweak has been assigned as true
```

Where the server is returning a response indicating a tweak is there but the tweak is not applied as expected within the listener. Is this your issue?

From what I can tell, the placement of the code actually matters here -- for example, if the code is in a helper method as opposed to directly in the listener, the chances for the above log are much more slim. If you add an arbitrary delay (I was using 500ms) the issue goes away entirely.

This appears to be a race condition where you are accessing the values for the tweaks as the experiment is being applied, resulting in the default value being returned instead of the actual tweak returned by the Mixpanel API. We will have to investigate the root cause further here, but you can resolve this by adding the above mentioned delay in the meantime.

**Comment by fred8** [comment] 2016-04-09 00:03
@ryanseams Yeah, that's exactly what we see.
In my opinion, you should fire the listener as soon as you know that the tweaks variable are correctly filled instead of introducing an arbitrary delay that could eventually failed sometimes.

Let me know if we we'll get a fix soon in the library. Our next enhancement is entirely based on that.

Thank you for your support!

**Comment by ryanseams** [comment] 2016-04-11 20:20
Hi @fred8 since the listener is used for surveys, notifications, and A/B tests it is not a problem with when the listener fires. The race condition would actually be between calling ```joinExperimentIfAvailable()``` and then executing the code to grab a tweak (i.e. ```boolean hiThere = HiThereTweak.get()```) immediately after the call to join an experiment.

@patedit @yinfeiru will have to look into this in detail to see if/when we can provide a fix for this issue.

**Comment by fred8** [comment] 2016-04-11 20:22
Hi @ryanseams 
So in that case why we couldn't have a listener that is explicit for the tweak variables?
For ex: addOnMixpanelUpdatesTweakVariableListener ?

**Comment by fred8** [comment] 2016-04-12 22:13
@ryanseams 
Any fixes?

**Comment by fred8** [comment] 2016-04-13 19:44
Hey @ryanseams,
Is there any additional problem? I'm not receiving the listener update callback anymore.
For the other part, do you have any fixes?

**Comment by ryanseams** [comment] 2016-04-13 22:53
@fred8 There should not be any problems with receiving the listener callback, provided there is a response coming from Mixpanel. If you are in a debug build with [Mixpanel debugging](https://mixpanel.com/help/reference/android#debugging_and_logging) enabled, you should be abled to see this response come through and then be processed -- can you confirm you are not getting a response?

Unfortunately for the main problem in this issue, the race condition between calling ```joinExperimentIfAvailable()``` and then grabbing tweak values using ```tweak.get()```, we do not have an immediate solution here. Our team will have to look into this in detail to figure out what makes the most sense, or, alternatively, we would be happy to review a PR if you already have a fix in mind.

In the meantime, one way I got around this was to add a delay before processing the tweaks (200ms seemed to work fine for me). Another potential solution is as you mentioned earlier to have a listener for tweaks, but this change would be at the SDK level and not just a workaround within your app.

**Comment by fred8** [comment] 2016-04-14 00:10
@ryanseams I will re double check with the mp debugging enabled.
For the tweaks listener, yeah, it's an SDK change... so that's why I wonder when we'll have an update for that

**Comment by yinfeiru** [comment] 2016-09-02 23:12
@fred8 Sorry for the late. Check this out https://github.com/mixpanel/mixpanel-android/pull/390. It will be available in the next release which is coming out today!

**Closed by yinfeiru** 2016-09-02 23:12 UTC
