### ISSUE TITLE
Inconsistent number of users for A/B tests

### ISSUE THREAD

**Issue by RomainPiel** [mixpanel/mixpanel-android#394] opened 2016-09-12 10:09 UTC
Hi, I'd like to understand how unique users are defined for A/B tests. I set up a tweak
```java
myTweak = MixpanelAPI.booleanTweak(TWEAK_NAME, false);
```
and used it in my first activity's `onCreate()` but for some reason sometimes mixpanel console is reporting multiple users for one user.
As a result, for a 50/50 experiment, the graph showing unique users per day is presenting some inconsistent data:
<img width="954" alt="screen shot 2016-09-12 at 10 59 09" src="https://cloud.githubusercontent.com/assets/464320/18432103/3461f950-78d8-11e6-95f5-7bc47c3eb891.png">

The app was launched by ~30 users in 3 days and we can see that we have more than 60 users for one variant on the first day.
I assume that a unique user is defined by one of those:
```java
MixpanelAPI mixpanelAPI = MixpanelAPI.getInstance(context, apiKey)
mixpanelAPI.identify(deviceIdentifier);
mixpanelAPI.getPeople().identify(deviceIdentifier);
```
And this should be pretty consistent in our app.

- What is defining a unique user?
- How can I see which data is sent to Mixpanel server? (The logs don't seem really helpful the identifier is always the same)

**Comment by cassiegamm** [comment] 2016-09-12 17:39
Hi @RomainPiel,

The distinct_id property determines unique users for all Mixpanel reports - A/B testing included. This property is visible in Live view and JQL and controlled using the identify methods that you've quoted in your initial post. 

Once you've enable [debugging and logging](https://mixpanel.com/help/reference/android#debugging_and_logging), you can identify the events that have been queued or sent to Mixpanel by searching for the substring: ` [{"event":` or  by for payloads associated with the log line:

> Successfully posted to https://api.mixpanel.com/track

Updates to people profiles can be identified by searching for payloads associated with the log line 

> Successfully posted to https://api.mixpanel.com/engage

If you could write in to support@mixpanel.com with a link to the report that shows only 30 users have open the app in the last 3 days, they will work with you to figure out what's going on.

**Comment by RomainPiel** [comment] 2016-09-14 12:02
Thanks @cassiegamm for your reply. I have sent an email.
It looks really strange, here is the number of unique users launching the app:
![screen shot 2016-09-14 at 12 03 49](https://cloud.githubusercontent.com/assets/464320/18511410/76424ace-7a7b-11e6-9fe2-f54d361935e9.png)

And here is the A/B test repartition now:
![screen shot 2016-09-14 at 12 07 58](https://cloud.githubusercontent.com/assets/464320/18511419/7f3cf5f2-7a7b-11e6-8ffa-b0a0db7f5412.png)

**Comment by cassiegamm** [comment] 2016-09-16 20:17
Thanks for the email and the pictures @RomainPiel! 

I'm going close this issue for now. We can reopen (or create a new issue) after we go through the logs and determine the root cause.

**Closed** 2016-09-16 20:39 UTC
