### ISSUE TITLE
identify() doens't change the DistinctID of events on the server

### ISSUE THREAD

**Issue by peterneubauer** [mixpanel/mixpanel-android#341] opened 2016-03-29 10:00 UTC
Hi there,
upon calling

    MixpanelAPI.getInstance(context, clientId).identify(ourUserUUID)

after login, we still see the events following this sent with something else than `ourUserUUID`, resulting in non-merged stream with the backend events that set the distinctID to `ourUserUUID`. Is that a but in the MP Android lib, since it works as expected on iOS?

**Comment by ryanseams** [comment] 2016-03-29 16:46
hi @peterneubauer ! I went ahead and downloaded your app to test out the signup flow and it appears there are two issues here:

1. you correctly call ```alias()``` when a user signs up, at which point what happens is Mixpanel creates a 1:1 mapping between the ID you provide (```ourUserUUID```) and the automatically assigned distinct ID on the device. this means whenever you send an update with ```ourUserUUID``` it will actually be recorded in Mixpanel with the automatically assigned distinct ID this value maps back to -- this is why you are seeing events sent with a different distinct ID, which is not a problem.

2. there is an issue where you are calling ```alias()``` on the client and sending an update from your server simultaneously, resulting in a race condition. essentially, the call from the client to tie the IDs together is resolving after the call from your server to create a profile and send events, resulting in these immediate server-side calls recording with a different distinct ID. you can resolve this by sending these immediate calls with the mixpanel distinct ID (can get this using ```getDistinctId()```) or by introducing a delay to ensure the alias resolves before the call goes out from your server.

let me know if you have questions regarding the above or if this can be better discussed over email regarding the specifics of your situation!

**Comment by peterneubauer** [comment] 2016-03-31 08:43
So, all our different clients (web, iOS, Android) should only call `alias` (btw, why are there different API calls for `alias` with one resp. two parameters on JS and Android/iOS?)?

Also, the server is sending with the `ourUserUUID` as distinctID. Should the server instead send a random distinctID and instead also call `alias` so all 4 MP clients have the same setup and we don't get a race condition since there is no stream with `ourUserUUID` in the system?

/peter

**Comment by millenbop** [comment] 2016-03-31 08:58
The problem is this use case:

1. User browses web, you track some events using an random `distint_id` (generated by MP).
2. User downloads app, launches app. You track some events using an another random `distint_id` (generated by MP).
3. User creates account from app using a server (tracked server side, and a new random `distint_id` is generated by MP), all the events from the web/app/server should be gathered to the same MP account, and the ID of this user should be `ourUserUUID`, not any of the three random `distint_id`´s used before.

How is this possible to solve with just one `alias`?

**Comment by ryanseams** [comment] 2016-03-31 17:57
Hi @peterneubauer and @millenbop :

No matter the platform, the usage pattern follows that you ```alias``` a user once (typically when they sign up) and then you ```identify``` them on all future logins. So, for JS/iOS/Android, you should call ```alias``` with ```ourUserUUID``` when a user signs up -- this will tie your unique identifier to the the randomized ```distinct_id``` on the current platform.

(Side note for @peterneubauer -- the alias methods all actually accept 2 arguments of the form ```(newID, oldID)``` but in JS we populate ```oldID``` with the ```distinct_id``` automatically if it is not provided. In your case the ```(newID, oldID)``` would take the form ```(ourUserUUID, distinct_id)```)

On any future platform, once you call ```identify``` with ```ourUserUUID```, all activity from this user will be merged with the previous activity as it ties back to the ```distinct_id```. This will miss any non-authenticated activity for the user on other platforms, however, it will cause any activity after authentication to be linked together cross platform.

In the usage case you outlined, the step to analyze in detail is step 3. At the point of creating an account from the app, you should call ```alias``` on this user with ```ourUserUUID``` -- this will ensure the previous calls from the device with ```distinct_id``` and the new calls from your server with ```ourUserUUID``` will be tied to the same user. Again, this will miss the web activity until the user logs in, but there is not a good way to "know" a user on multiple platforms is the same until they log in.

You can find a detailed explanation of cross platform identity tracking [here](https://mixpanel.com/blog/2015/09/21/community-tip-maintaining-user-identity). Does the above solve the usage case you outlined?

**Comment by peterneubauer** [comment] 2016-03-31 18:11
Ok,
SI we should call alias from the server event that creates the account, and
only do identify from all platforms then. One thing is the timing, but
possibly we can delay the calls after login a bit.

I ta strange though that there is now way to link the old events before
identify to the right user - we know that they belong there but there is no
way of telling that mix panel? It's not great since we can't follow a
user's on boarding journey then - part of the point of the whole system
IMHO?

**Comment by ryanseams** [comment] 2016-03-31 18:27
@peterneubauer You can call ```alias``` from the server, however, this will require you pass the ```distinct_id``` to your server before an ```alias``` call can be made. As mentioned in my previous reply the form of your alias arguments would be ```(newID, oldID)``` and since the ```oldID``` is not stored on your server you would need to pass it along before you can make the ```alias``` call. You can find some further info on this process [here](https://mixpanel.com/blog/2015/10/12/community-tip-server-side-identity-management), or you can just make the ```alias``` call from the client side.

As for the events, calling ```alias``` when a user signs up and then ```identify``` whenever they login will link the old events before a user signed up to the new events after a user signed up. The case this does not cover is events when a user is unauthenticated on a new platform -- until this user signs in there is no way to know this is the same user who signed up on another device. You should be able to follow a user's on-boarding journey without issues.

**Comment by peterneubauer** [comment] 2016-04-07 13:14
Hi there,
now we have changed the signup flow to do the alias upon signup, and after that only use identify. However, if we log in/log out multiple times, the streams are still not merged in MP into one People. Can you please try http://android-releases.mapillary.io/app-release_184-MP.apk and let us know if this is the right flow of events?

**Comment by peterneubauer** [comment] 2016-04-11 07:10
Bump?

**Comment by ryanseams** [comment] 2016-04-11 20:16
Hi @peterneubauer I went ahead and tested the version of the app you sent over. Are you sure you are calling ```alias``` on the username when signing up? I am not seeing an alias created in Mixpanel, and my profile is breaking upon sign up within the app as ```identify``` is definitely being called with my username:

![image](https://cloud.githubusercontent.com/assets/9201737/14440988/6bcea3e4-ffe7-11e5-8856-4834e169ba86.png)

The distinct ID of a user should remain consistent across all interactions with the app and it does not appear to be happening here since ```alias``` is not called.

**Comment by peterneubauer** [comment] 2016-04-14 08:24
well, this is the exact code that is being called (I can get you access to our repo if you need):
              
                MixpanelAPI instance = MixPanel.instance(SignUpActivity.this);               
                data.putString(AccountManager.KEY_ACCOUNT_NAME, email);
                data.putString(AccountManager.KEY_ACCOUNT_TYPE, MapillaryAccountConstants.AUTHTOKEN_TYPE_FULL_ACCESS);
                data.putString(AccountManager.KEY_AUTHTOKEN, tokens[0]);
                data.putString(PARAM_UPLOAD_TOKEN, tokens[1]);
                data.putString(PARAM_USERNAME, tokens[2]);
                String mail = tokens[3];
                data.putString(PARAM_EMAIL, mail);
                Utils.saveProjects(SignUpActivity.this, tokens[4]);
                String user_uuid = tokens[5];
                instance.alias( user_uuid, instance.getDistinctId());
                instance.identify(user_uuid);
                instance.getPeople().set("Registered via", "Android");
                instance.getPeople().set("$email", mail);
                instance.getPeople().set("Date created account", new Date());

So alias is called before identify. Not sure why that is not honored? Do you have any possibility to track an ALIAS call in the MixPanel backend?

**Comment by ryanseams** [comment] 2016-04-14 22:59
I checked on our backend and the value ```ryanseamsmp``` was never aliased to the automatically assigned distinct ID in the screenshot. Is it possible to turn on [debug logging](https://mixpanel.com/help/reference/android#debugging_and_logging) on this build so I can watch the calls go out from the device?

As for the issue with ```$email``` never showing up, you will need to make one more call to ```instance.getPeople().identify(user_uuid)``` to flush the people updates to our servers. Without the call to ```getPeople().identify()``` the calls will be queued on the device until this method is called.

**Comment by peterneubauer** [comment] 2016-04-18 12:22
Thanks @ryanseams  for the debug hint - I think things are working correctly now!

**Comment by patedit** [comment] 2016-08-29 19:19
Thanks @peterneubauer and @ryanseams for your endless help!

**Closed by patedit** 2016-08-29 19:19 UTC
