### ISSUE TITLE
Crashes on N

### ISSUE THREAD

**Issue by Macarse** [mixpanel/mixpanel-android#363] opened 2016-05-16 17:16 UTC
I am seeing some crashes related to N

The stacktrace is the following:

```
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:772)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at com.android.okhttp.ConnectionPool.addConnection(ConnectionPool.java:208)
	at com.android.okhttp.ConnectionPool.recycle(ConnectionPool.java:198)
	at com.android.okhttp.OkHttpClient$1.recycle(OkHttpClient.java:113)
	at com.android.okhttp.internal.http.HttpConnection$AbstractSource.endOfInput(HttpConnection.java:377)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:426)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
	at com.mixpanel.android.util.HttpService.slurp(SourceFile:169)
	at com.mixpanel.android.util.HttpService.performRequest(SourceFile:127)
	at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(SourceFile:421)
	at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(SourceFile:388)
	at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(SourceFile:260)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by yinfeiru** [comment] 2016-08-31 20:32
@Macarse Do you know a way to reproduce it? I've tried it on the emulator with Android N and didn't see this issue. I did a bit of research and found out that this type of exception always happens when the okhttp lib tries to spawn a new thread after your app is shutdown. So, I'm wondering if 

1. your app was shutdown due to another crash before this
2. the device was low on memory
3. it's related to the MixpanelActivityLifecycleCallbacks as we try to flush the queue if the app is backgrounded

If you can provide me the way of reproducing it, I'll be happy to try it out.

**Comment by Macarse** [comment] 2016-08-31 20:42
@yinfeiru I am not seeing it anymore in my crashes. I might have fixed it with https://code.google.com/p/android/issues/detail?id=56296

basically: 
```
    private void checkAppReplacingState() {
        if (getResources() == null) {
            Process.killProcess(Process.myPid());
        }
    }

```

**Comment by patedit** [comment] 2016-09-06 17:30
Thanks @Macarse for the update and the link. Closing this issue 👍

**Closed by patedit** 2016-09-06 17:30 UTC
