### ISSUE TITLE
Issue - No Activity found to handle Intent 

### ISSUE THREAD

**Issue by kemalatli** [mixpanel/mixpanel-android#690] opened 2020-03-31 10:55 UTC
After upgrading the mixpanel version to 5.7.0, we started seeing activity not found issues in crash logs. It looks like a deep link intent couldn't be resolved to our launcher activity. Mixpanel doesn't seem to handle activity intents gracefully. Here is the logs for further information:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{me.picker.android/com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat={ "deep_link":"xxx://open?addPick" } }
       at android.app.ActivityThread.performLaunchActivity + 3121(ActivityThread.java:3121)
       at android.app.ActivityThread.handleLaunchActivity + 3264(ActivityThread.java:3264)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1955(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7063(ActivityThread.java:7063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 965(ZygoteInit.java:965)
```

```
Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat={ "deep_link":"xxx://open?addPick" } }
       at android.app.Instrumentation.checkStartActivityResult + 2022(Instrumentation.java:2022)
       at android.app.Instrumentation.execStartActivity + 1677(Instrumentation.java:1677)
       at android.app.Activity.startActivityForResult + 4689(Activity.java:4689)
       at android.app.Activity.startActivityForResult + 4647(Activity.java:4647)
       at android.app.Activity.startActivity + 5008(Activity.java:5008)
       at android.app.Activity.startActivity + 4976(Activity.java:4976)
       at com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity.onCreate + 36(MixpanelNotificationRouteActivity.java:36)
       at android.app.Activity.performCreate + 7327(Activity.java:7327)
       at android.app.Activity.performCreate + 7318(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate + 1275(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity + 3101(ActivityThread.java:3101)
       at android.app.ActivityThread.handleLaunchActivity + 3264(ActivityThread.java:3264)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1955(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7063(ActivityThread.java:7063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 965(ZygoteInit.java:965)
```

**Comment by davidtcdeveloper** [comment] 2020-04-22 18:19
We are facing a similar issue here. We launched a push notification with a link to open in a browser. Some devices are launching this error:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.involves.agilepromoter/com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://club.involves.com/... }
       at android.app.ActivityThread.performLaunchActivity + 2789(ActivityThread.java:2789)
       at android.app.ActivityThread.handleLaunchActivity + 2872(ActivityThread.java:2872)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage + 1595(ActivityThread.java:1595)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 164(Looper.java:164)
       at android.app.ActivityThread.main + 6543(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 440(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main + 810(ZygoteInit.java:810)
```
We are using version Mixpanel SDK Android version 5.8.2.

**Comment by mayurdhurpate** [comment] 2020-10-12 10:11
Facing the same crash for our notifications, for many of our users. Multiple device categories impacted.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pruoo.pruoo_app/com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= imumz://app/feedPost/k4NoaDR92RWyA7GNNBhe }
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
Caused by:

```
Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat= imumz://app/feedPost/k4NoaDR92RWyA7GNNBhe }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2241)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1895)
       at android.app.Activity.startActivityForResult(Activity.java:5205)
       at android.app.Activity.startActivityForResult(Activity.java:5163)
       at android.app.Activity.startActivity(Activity.java:5534)
       at android.app.Activity.startActivity(Activity.java:5502)
       at com.mixpanel.android.mpmetrics.MixpanelNotificationRouteActivity.onCreate(MixpanelNotificationRouteActivity.java:43)
       at android.app.Activity.performCreate(Activity.java:7815)
       at android.app.Activity.performCreate(Activity.java:7804)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by zihejia** [comment] 2020-11-25 17:44
Sorry for the late response. https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.5 was released to address this issue. I'm closing this one now, please feel free to reopen it if the problem still exists. Thanks!

**Closed by zihejia** 2020-11-25 17:44 UTC
