### ISSUE TITLE
On the very first launch after the initialization of the MP instance the lister onMixpanelUpdatesReceived is not called

### ISSUE THREAD

**Issue by fred8** [mixpanel/mixpanel-android#362] opened 2016-05-12 19:02 UTC
Step to repro:

Turn on an experiment
Uninstall any old version of the sample app.
Install and launch the app.
Tweak value is “none” and not “A” on the first launch.

**Comment by ryanseams** [comment] 2016-05-12 21:58
The ```onMixpanelUpdatesReceived``` listener is designed to be called whenever an updated response is received from the Mixpanel server and not when the app initializes. Until a response is received from Mixpanel to the device, the device has no idea what A/B test the user is a part of.

As such, the above behavior is expected that the receiver will not run when the app launches, and rather when the first update is received. As part of initialization the Mixpanel SDK goes and looks for a response from our server and, should there be a response, then ```onMixpanelUpdatesReceived``` will be called. During this time as the device waits for a response you would see the Tweak value as the default.

Are you not seeing the receiver called after the response is received from the Mixpanel server?

**Comment by nbarishok** [comment] 2016-07-12 13:21
I've faced the same problem. 
And there is some confusing thing, along these lines:

**DecideChecker.java**
`                DecideChecker.Result e = this.runDecideCheck(updates.getToken(), distinctId, poster);
                updates.reportResults(e.surveys, e.notifications, e.eventBindings, e.variants);`

Here the **e.variants** is empty. And actually the response from server is  **{"notifications":[],"surveys":[]}**
So seems like the variants aren't even planned to be fetched.

@ryanseams could you elaborate a bit on this behavior?

**Comment by ryanseams** [comment] 2016-07-12 17:28
Hi @nbarishok -- This issue was actually resolved by working with the submitter offline. In this specific case the user was performing a targeted A/B test, which requires a delay to get the expected test since a brand new user will not meet the targeting criteria until their data is uploaded to Mixpanel as explained [here](https://mixpanel.com/help/questions/articles/how-can-i-effectively-ab-test-the-very-first-screen-or-sign_up-flow-of-my-app) in more detail.

In general, the ```onMixpanelUpdatesReceived``` will only be called when an A/B test is entered or exited. If you receive an empty response from our decide server (like the one you pointed out) and the user was not in an A/B test already, then the listener will not be called. It will only be called when the status of a user's A/B test changes from what is on the device versus the server.

Can you indicate if you are expecting the listener to run and elaborate a bit more on what your problem is here?

**Comment by yinfeiru** [comment] 2016-08-31 21:40
Closing as it's an expected behavior

**Closed by yinfeiru** 2016-08-31 21:40 UTC
