### ISSUE TITLE
UI Lag on Lollipop

### ISSUE THREAD

**Issue by snard6** [mixpanel/mixpanel-android#178] opened 2015-03-05 23:48 UTC
While testing our app on Lollipop we noticed a huge decrease in performance on Lollipop devices.  After much debugging we narrowed down the issue to MixPanel.  After removing the MixPanel init everything is nice and smooth:
MixpanelAPI.getInstance(this, MIXPANEL_TOKEN);

This is fairly easy to reproduce by adding a height animator on any view.  The more complex the view the more janky the result, but even a view with a single color will lag enough to be noticed:
        ValueAnimator animator = ValueAnimator.ofInt(0, 2000);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator valueAnimator) {
                ViewGroup.LayoutParams layoutParams = view.getLayoutParams();
                layoutParams.height = (Integer) valueAnimator.getAnimatedValue();
                view.setLayoutParams(layoutParams);
            }
        });
        animator.setDuration(3000);
        animator.start();

We love MixPanel, but until we have a solution for this lag will most likely have to remove it.  Please let me know how I can help you resolve it.

**Comment by joeatwork** [comment] 2015-03-06 18:41
Hi, @snard6 ! I'm sorry you're having problems!

I'd love to get a bit more information about the circumstances- If you don't mind, I'd love to get answers to the following questions (either here, or at support@mixpanel.com if you're not comfortable posting your answers in public)

Of course, the issues you're seeing are ours to solve, so please don't feel obligated to answer, but any information you can give us will help us fix the problem.

Thanks! My questions follow:

- are you observing these problems in the emulator or on devices, or both?
- If you add the following metadata elements to your app, does the problem go away? 
```
  <meta-data android:name="com.mixpanel.android.MPConfig.DisableEmulatorBindingUI"
       android:value="true" />
  <meta-data android:name="com.mixpanel.android.MPConfig.DisableGestureBindingUI"
       android:value="true" />
```
- Are you using codeless event binding? If so, how many events are you using?
- Are there interventions other than height animation that seem to cause problems? (Something to try is any other animation that forces a global change in the layout, for example making a view disappear and reappear)
- If you downgrade to an earlier version (say 4.4.1) does the issue go away?
- Can you reproduce the issue on any other platform than Lollipop? Does KitKat have the same problem?
- Finally, what/how are you tracking? Are you tracking based on UI changes?

**Comment by snard6** [comment] 2015-03-16 17:57
Hey @joeatwork ,

Sorry for the slow reply, it has been busy around here.  Here's the answers to your questions:

- On device.  We've tested on the Moto X and Nexus 5 (both Lollipop) and saw the problem.  It doesn't happen on our LG G3 or Htc One (KitKat & Jellybean).

- I added that metadata and the problem stayed.

- Yes, we had 5 codeless events.  I removed them all, deployed, and tried again.  The problem still remained.

- The whole app appears slower.  It appears to be most obvious when a re-layout happens (such as the height animation).  But it is also super noticeable by simply calling getActionBar().hide() as well as other places in the app.

- Downgrading wasn't entirely straightforward, I'm guessing the API must have changed since then.  So I gave up trying.

- Actually, I'm able to reproduce this without tracking anything.  After removing every single event in the app, I still see the lag.  If I remove the initialize call it disappears completely.

Thanks for looking into this.
Brad

**Comment by joeatwork** [comment] 2015-03-16 18:07
Thanks for your response! This is good information for us- we can use it to try and replicate your issue!

Thanks again (and thanks for your report!)

**Comment by gastonsanguinetti** [comment] 2015-04-27 21:44
I have the same problem! Please let me know if there is any update on this bug or if I can help giving you more information.

**Comment by sgallego** [comment] 2015-05-26 06:23
Hi,
is there any update about this bug? I have the same problem too.

**Comment by joeatwork** [comment] 2015-05-26 16:12
Thanks for your report, @sgallego ! We've been working on reproducing this. If either you or @snard6 would feel comfortable sharing your layout files with Mixpanel directly (you can email joe@mixpanel.com or support@mixpanel.com) that might help.

It's likely the core of the issue is associated with codeless event tracking, which requires a traversal of the view hierarchy to bind it's events, but since @snard6 has reported that no codeless events have been deployed, the library really shouldn't be traversing anything at all. We'll continue to try and reproduce the issue here.

**Comment by joeatwork** [comment] 2015-06-15 17:09
Investigators - try this with layouts containing many separate fragments, and investigate the use of SlidingMenuFragmentActivity from https://github.com/jfeinstein10/SlidingMenu

**Comment by gastonsanguinetti** [comment] 2015-07-23 22:53
It´s any update in this case? @joeatwork ,in our app we are using SlidingMenu and a couple of fragments as well.

**Comment by gastonsanguinetti** [comment] 2015-07-23 23:07
Update: I've deleted all the codeless events and the performance problem has gone in Android 5! :)

**Comment by jbwyme** [comment] 2015-07-23 23:12
@gatonsanguinetti thanks for the update sounds like you've isolated the
issue so we'll dive into it.

On Thu, Jul 23, 2015 at 4:07 PM, gastonsanguinetti <notifications@github.com

**Comment by assizic** [comment] 2015-12-03 09:03
Any progress with this issue? We've been seeing it as well when using MixPanel with version > 4.5.3.

**Comment by yinfeiru** [comment] 2016-01-26 00:08
@assizic Thanks for writing in. I'll be working on this in the next few days.

**Comment by assizic** [comment] 2016-01-26 08:13
Thanks, @yinfeiru! We're looking forward to it. We currently can't use several new features introduced in  latest versions (like AB testing), and it's holding us back.

**Comment by yinfeiru** [comment] 2016-01-27 23:15
@assizic I'm trying to reproduce this issue but no luck so far. Is it possible if you provide me a simple demo project which has this issue? Or, can you provide me your layout file?

**Comment by joeatwork** [comment] 2016-01-27 23:39
@yinfeiru try it with a large number of edits, and a deep view hierarchy

**Comment by yinfeiru** [comment] 2016-01-28 00:03
@joeatwork cool. will try.

**Comment by assizic** [comment] 2016-01-28 13:17
@yinfeiru I'll try to create a demo project that shows the problem. Will update soon.

**Comment by yinfeiru** [comment] 2016-01-28 17:27
@assizic Fantastic!!

**Comment by assiziv** [comment] 2016-02-07 13:06
@yinfeiru I'm currently unable to provide a project to demonstrate the issue, as it requires our core logic that I can't send (we build these views by code and not from an XML).
However - I see that it it is considerably more sluggish when the view is complex, or the hierarchy is deep. Have you tried building very complex views? The problem is very visible when we have multiple animations on a complex view.
Some more things: Have you seen my comment from Dec 3 '15? The issue is related to the Handler (the workerThread) in AnalyticsMessages. Does it run periodically on the views tree or something? If you want me to test things, let me know. This thing is really holding back our AB testing.
Thanks!

**Comment by yinfeiru** [comment] 2016-02-08 19:16
@assiziv Thanks for letting me know! @patedit and I have tried various things - deep hierarchy, adding fragments, adding animation, etc. Unfortunately, we were still not able to reproduce it. We'll keep trying and let you know if we have some break through.

As far as I know, his issue seems to be related to the ViewCrawler class. It parses through the whole view hierarchy to apply A/B changes and it's introduced in 4.6.

**Comment by assiziv** [comment] 2016-02-10 15:54
@yinfeiru The problem seems to be resolved with latest release (4.8.0) :)
I'll update you if I see something after using it for a while. Thanks!

**Comment by patedit** [comment] 2016-02-10 16:09
Thanks for the update (and for updating!) @assiziv!

**Closed** 2016-02-29 17:58 UTC
Labels: bug

**Comment by yahor-makouski-epam** [comment] 2016-03-05 12:21
I can still reproduce the issue as long as we have a big enough amount of events created in the account.

here is the trace with confirmation mixpanel does a lot of work on ui:
https://drive.google.com/file/d/0B9_5dr6in8cWRmQwZzNaUWpLQnM/view?usp=sharing

**Comment by joshln87** [comment] 2016-07-11 03:35
Any update on this? I'm still getting lag from codeless events. Very obvious when using SwipeRefreshLayout. Overscrolling can see obvious lag in the spinner.
