### ISSUE TITLE
showSurveyById doesn't seem to work, or works in a non obvious and useless way

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-android#192] opened 2015-03-25 18:34 UTC
Works intermittently, but we can reproduce a case where there are multiple surveys including the id selected coming from the Mixpanel decide endpoint, but calls to showSurveyById don't show. This could be because the surveys are marked as shown too early, or they overflow the buffer for available surveys- both of these states are expected and reasonable, but they make showSurveyById really hard to use reliably.

Revisit the mechanism, figure out exactly what is going on, and either change it or provide some sort of affordance in the API so people can actually use this method.

**Comment by folkyatina** [comment] 2015-10-06 15:35
Met this bug too. 
Survey is already marked as seen when you retrieve it using getSurveyIfAvailable() and can't be shown using showSurveyById() as it checks if it's already seen. 
But deprecated showSurvey() still works as intended.

**Closed** 2017-09-12 00:11 UTC
Labels: bug
