### ISSUE TITLE
I need firebase even when I am not using messaging.

### ISSUE THREAD

**Issue by thinkong** [mixpanel/mixpanel-android#610] opened 2019-07-25 00:15 UTC
Hi

I have implemented mixpanel in my app. On startup it says
```
2019-07-25 09:06:45.587 6198-6198/com.mycompany.mygame I/s.mygame: Rejecting re-init on previously-failed class java.lang.Class<com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
2019-07-25 09:06:45.587 6198-6198/com.mycompany.mygame I/s.mygame:     at com.mixpanel.android.mpmetrics.MixpanelAPI com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(android.content.Context, java.lang.String) (MixpanelAPI.java:369)
2019-07-25 09:06:45.587 6198-6198/com.mycompany.mygame I/s.mygame:     at void com.mycompany.mygame.gameactivity.onCreate(android.os.Bundle) (gameactivity.java:279)
2019-07-25 09:06:45.587 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7327)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7318)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:3088)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3251)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1948)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.os.Looper.loop() (Looper.java:214)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7045)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:965)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.mycompany.mygame-weQ6NHhKQsu2gahWPxXSCw==/base.apk"],nativeLibraryDirectories=[/data/app/com.mycompany.mygame-weQ6NHhKQsu2gahWPxXSCw==/lib/arm, /data/app/com.mycompany.mygame-weQ6NHhKQsu2gahWPxXSCw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at com.mixpanel.android.mpmetrics.MixpanelAPI com.mixpanel.android.mpmetrics.MixpanelAPI.getInstance(android.content.Context, java.lang.String) (MixpanelAPI.java:369)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void com.mycompany.mygame.gameactivity.onCreate(android.os.Bundle) (gameactivity.java:279)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.Activity.performCreate(android.os.Bundle, android.os.PersistableBundle) (Activity.java:7327)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7318)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1271)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:3088)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at android.app.Activity android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.app.servertransaction.PendingTransactionActions, android.content.Intent) (ActivityThread.java:3251)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.servertransaction.LaunchActivityItem.execute(android.app.ClientTransactionHandler, android.os.IBinder, android.app.servertransaction.PendingTransactionActions) (LaunchActivityItem.java:78)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.servertransaction.TransactionExecutor.executeCallbacks(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:108)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.servertransaction.TransactionExecutor.execute(android.app.servertransaction.ClientTransaction) (TransactionExecutor.java:68)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1948)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.os.Looper.loop() (Looper.java:214)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7045)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
2019-07-25 09:06:45.588 6198-6198/com.mycompany.mygame I/s.mygame:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:965)
```
If I do include firebase messaging this will go away. 
Is this message ok? 
It seems to be working but this is bothering me.
This seems to happen on my Galaxy S9 with Android 9 on it.

**Comment by suren-assetowl** [comment] 2019-08-01 09:25
I am getting same error. Any one for the rescue here?

**Comment by patedit** [comment] 2019-08-02 19:44
I've personally never seen that message. Could you paste the output when the SDK is initialized for the first time? Can you confirm that you don't add `MixpanelFCMMessagingService` on your `AndroidManifest.xml` file? thank you!

**Comment by patedit** [comment] 2019-11-19 20:08
This will be fixed in the next release (https://github.com/mixpanel/mixpanel-android/commit/1aefdc74af179f3b5eea435a907ed355707cc07c)

**Closed by patedit** 2019-11-19 20:08 UTC

**Comment by mariah-smith25** [comment] 2020-02-12 18:13
I'm still getting these errors with v5.6.8

**Comment by patedit** [comment] 2020-02-19 00:05
Hi @mariah-smith25 - Are you adding `MixpanelFCMMessagingService` receiver on you` AndroidManifest.xml` file?

**Comment by mariah-smith25** [comment] 2020-02-19 17:45
@patedit Hi, thanks for responding. I do not have this in my AndroidManifest. I might be seeing a different issue as our logcat output is slightly different than OP. We're seeing 
`
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi: Rejecting re-init on previously-failed class java.lang.Class<com.appsflyer.FirebaseMessagingServiceListener>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at com.appsflyer.internal.s$d com.appsflyer.internal.s.ॱ(android.content.Context) (:105)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore.ॱ(android.content.Context, java.util.Map) (:2170)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at java.util.Map com.appsflyer.AppsFlyerLibCore.ॱ(com.appsflyer.internal.j) (:1950)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore.ˏ(com.appsflyer.internal.j) (:1554)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore.ॱ(com.appsflyer.AppsFlyerLibCore, com.appsflyer.internal.j) (:85)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore$c.run() (:3287)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:459)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (ScheduledThreadPoolExecutor.java:301)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AFExecutor$4$3.run() (:31)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.lang.Thread.run() (Thread.java:764)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.trala.learn.violin-oTXEXnlGl00VpKiDPqIf2w==/base.apk"],nativeLibraryDirectories=[/data/app/com.trala.learn.violin-oTXEXnlGl00VpKiDPqIf2w==/lib/arm64, /data/app/com.trala.learn.violin-oTXEXnlGl00VpKiDPqIf2w==/base.apk!/lib/arm64-v8a, /system/lib64]]
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at com.appsflyer.internal.s$d com.appsflyer.internal.s.ॱ(android.content.Context) (:105)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore.ॱ(android.content.Context, java.util.Map) (:2170)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at java.util.Map com.appsflyer.AppsFlyerLibCore.ॱ(com.appsflyer.internal.j) (:1950)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore.ˏ(com.appsflyer.internal.j) (:1554)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore.ॱ(com.appsflyer.AppsFlyerLibCore, com.appsflyer.internal.j) (:85)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AppsFlyerLibCore$c.run() (:3287)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:459)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (ScheduledThreadPoolExecutor.java:301)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void com.appsflyer.AFExecutor$4$3.run() (:31)
2020-02-19 11:42:24.213 18316-18395/? I/la.learn.violi:     at void java.lang.Thread.run() (Thread.java:764)`

I even put in the recommended proguard statements to no avail. Should I file a separate ticket for this issue?

**Comment by patedit** [comment] 2020-02-19 19:06
@mariah-smith25 Thanks for providing that log for me. Notice that Mixpanel does not appear on your stacktrace and it seems that the problem is coming from Appsflyer. You might have better luck if you contact them directly.
