### ISSUE TITLE
Can't write track_message to server

### ISSUE THREAD

**Issue by pepos** [mixpanel/mixpanel-android#253] opened 2015-08-19 15:40 UTC
Hi, I tried to implement library version 4.6.x on my Android app. First call to MixpanelAPI.track is working but the next calls are giving me the next error:

```
E/MixpanelAPI.ViewCrawler﹕ Can't write track_message to server
    com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
            at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:147)
            at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
            at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
            at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:171)
            at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:158)
            at android.util.JsonWriter.flush(JsonWriter.java:384)
            at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:646)
            at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:306)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
E/MixpanelAPI.ViewCrawler﹕ Can't close writer.
    com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
            at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:147)
            at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
            at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
            at java.io.FilterOutputStream.close(FilterOutputStream.java:61)
            at java.io.BufferedOutputStream.close(BufferedOutputStream.java:152)
            at java.io.OutputStreamWriter.close(OutputStreamWriter.java:141)
            at android.util.JsonWriter.close(JsonWriter.java:393)
            at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:651)
            at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:306)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

The version 4.5.3 is working like a charm. No errors.

**Comment by dbachelder** [comment] 2015-08-19 16:00
I keep meaning to log this as well.. happens quite frequently.

**Comment by dbachelder** [comment] 2015-08-21 20:37
The view crawler should have a meta option to disable.

**Comment by dbachelder** [comment] 2015-08-21 20:48
We have resorted to reflection to avoid the performance hit and log noise.

```
  public MixpanelAPI provideMixpanel(Application ctx) {
    MixpanelAPI instance = MixpanelAPI.getInstance(ctx, ctx.getString(getMixPanelResourceId()));
    try {
      Field field = MixpanelAPI.class.getDeclaredField("mTrackingDebug");
      field.setAccessible(true);
      field.set(instance, null);
    } catch (Exception e) {
      e.printStackTrace();
    }
    return instance;
  }
```

**Comment by pepos** [comment] 2015-08-21 21:41
Thank you @dbachelder, this workaround is working with the last version (4.6.3)!

**Comment by ngheungyu** [comment] 2015-08-26 07:30
same error for me, it's better to support disabling ViewCrawler. Thanks @dbachelder for the workaround.

**Comment by Nivl** [comment] 2015-11-23 23:01
Same issue on 4.7, @dbachelder workaround is still working.

**Comment by yinfeiru** [comment] 2016-01-26 21:44
We are working on providing a way to disable the ViewCrawler. I'll close this one and post updates to #276.

**Comment by pawanchauhan05** [comment] 2016-07-20 11:14
i am facing the same issue, what should i do ?

**Comment by ngheungyu** [comment] 2016-07-20 13:22
@pawanchauhan05 check #278

**Comment by yeissonoviedo** [comment] 2016-08-16 10:07
This error still occurs on 4.9.1. What's the purpose of the ViewCrawler? Is it ok to just disable it as mentioned in the PR?

**Comment by patedit** [comment] 2016-09-29 21:32
If it's confusing you guys we will try either remove the logs or add a gesture to connect from the emulator to AB test.

**Closed** 2016-10-31 19:50 UTC

**Comment by pecabum** [comment] 2016-11-23 09:56
same for 4.9.2

**Comment by ech0s7r** [comment] 2018-04-27 14:12
Facing the same issue here with version 5.4.0.

Here the stacktrace:
```
2018-04-27 15:04:33.858 30666-30704/com.example.demo E/MixpanelAPI.ViewCrawler: Can't write track_message to server
    com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
        at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:146)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at android.util.JsonWriter.flush(JsonWriter.java:384)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:690)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2018-04-27 15:04:33.859 30666-30704/com.example.demo E/MixpanelAPI.ViewCrawler: Can't close writer.
    com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
        at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.close(EditorConnection.java:159)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:160)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at android.util.JsonWriter.close(JsonWriter.java:393)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:696)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by wgins** [comment] 2018-04-27 14:45
Hey @ech0s7r -- you should be able to disable the ViewCrawler via:

```
<meta-data android:name="com.mixpanel.android.MPConfig.DisableViewCrawler"
            android:value="true" />
```
More info can be found [here](https://github.com/mixpanel/mixpanel-android/blob/6f2aa82f791f42dd27b67339685af09390c3b7d1/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java#L79-L80).

**Comment by ech0s7r** [comment] 2018-04-27 15:03
Thanks @wgins, 

It looks more like a workaround to address this issue, do you have in mind to fix the root cause?

Thanks,
ech0s7r

**Comment by lidorDF** [comment] 2021-06-01 10:05
Still getting this error, version in build gradle:  'mixpanel-android:5.9.1'
